import { Search } from "lucide-react";
import { searchSeals, SEAL_MATERIALS, SUPTEX_SEALS } from "@/lib/engineering-tools/seals";
import { TECHNICAL_SOURCES } from "@/lib/engineering-tools/standards";
import { SourceNote } from "../source-note";

export default async function SealsPage({searchParams}:{searchParams:Promise<{q?:string;material?:string}>}){
 const params=await searchParams; const query=params.q??""; const material=params.material??""; const results=searchSeals(query,material);
 return <main className="grid gap-5"><header><p className="oc-kicker text-muted-foreground">Üretici kataloğu</p><h2 className="text-xl font-semibold">Suptex keçe ölçüleri</h2><p className="mt-1 text-sm text-muted-foreground">Kod, mil, yuva, yükseklik, tip, malzeme veya M.S.A. ile arayın. Birleşik katalog ölçüleri özgün biçimiyle korunur.</p></header><form className="grid gap-3 border bg-card p-4 sm:grid-cols-[minmax(0,1fr)_14rem_auto]"><label className="grid gap-1 text-sm">Arama<input name="q" defaultValue={query} className="h-10 border bg-background px-3 text-base pointer-fine:text-sm" placeholder=""/></label><label className="grid gap-1 text-sm">Malzeme<select name="material" defaultValue={material} className="h-10 border bg-background px-3"><option value="">Tümü</option>{SEAL_MATERIALS.map((item)=><option key={item}>{item}</option>)}</select></label><button className="oc-tap mt-auto inline-flex h-10 items-center justify-center gap-2 border border-primary bg-primary px-4 text-sm text-primary-foreground"><Search className="size-4"/>Ara</button></form><div className="flex flex-wrap items-center justify-between gap-2 text-sm"><span><strong>{results.length}</strong> sonuç gösteriliyor</span><span className="text-muted-foreground">Toplam {SUPTEX_SEALS.length.toLocaleString("tr-TR")} katalog kaydı · en çok 80 sonuç</span></div><section className="overflow-hidden border bg-card"><table className="oc-tablet-table oc-compact-mobile-table w-full text-sm"><thead className="bg-muted/45 text-left text-[11px] uppercase text-muted-foreground"><tr><th className="px-3 py-2">Suptex kodu</th><th className="px-3 py-2">Mil çapı</th><th className="px-3 py-2">Yuva çapı</th><th className="hidden px-3 py-2 sm:table-cell">Yükseklik</th><th className="hidden px-3 py-2 md:table-cell">Tip</th><th className="px-3 py-2">Malzeme</th><th className="hidden px-3 py-2 lg:table-cell">M.S.A.</th></tr></thead><tbody>{results.map((row,index)=><tr className="border-t" key={`${row.code}-${index}`}><td data-label="Suptex kodu" className="max-w-[13rem] whitespace-normal px-3 py-2 font-mono [overflow-wrap:anywhere]">{row.code}</td><td data-label="Mil" className="px-3 py-2 font-mono">{row.shaftDiameter} mm<span className="block text-[11px] text-muted-foreground sm:hidden">Yükseklik: {row.height} mm · {row.type}</span></td><td data-label="Yuva" className="px-3 py-2 font-mono">{row.housingDiameter} mm</td><td data-label="Yükseklik" className="hidden px-3 py-2 font-mono sm:table-cell">{row.height} mm</td><td data-label="Tip" className="hidden px-3 py-2 md:table-cell">{row.type}</td><td data-label="Malzeme" className="px-3 py-2">{row.material}</td><td data-label="M.S.A." className="hidden px-3 py-2 lg:table-cell">{row.msa||"—"}</td></tr>)}</tbody></table></section><SourceNote source={TECHNICAL_SOURCES.suptex}/></main>
}
