'use client';
import { useRef, useState } from 'react';
import { Mail, FileCode2, Workflow, History, Settings2, CheckCircle2, AlertCircle, Eye, Send, Plus, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { USER_ROLES, USER_ROLE_LABELS, type UserRole } from '@/lib/roles';
import { eventLabels, eventTypes, fieldLabels, modeLabels, statusLabels, rowToRule, type RuleInput, type RuleRow, type TemplateContent, type Recipient } from '@/lib/email-center/model';
import type { emailCenterData, EmailCommand } from '@/lib/email-center/service';

type CenterData=Awaited<ReturnType<typeof emailCenterData>>;
type Preview={payload:{subject:string;html:string;text:string};recipients:Recipient[];testAddress:string};
type DeliveryDetail={id:string;status:string;payload:{subject?:string;html?:string;text?:string};provider_events:Record<string,string>;reasons:string[];first_attempt_at:string|null;attempts:number;provider_id:string|null};
const date=(value:string|null)=>value?new Date(value).toLocaleString('tr-TR'):'—';
const panel='rounded-xl border bg-card p-4 sm:p-5';
const control='oc-tap min-h-10 w-full rounded-md border bg-background px-3 py-2 text-base md:text-sm';
const tabs=[{key:'overview',label:'Genel Bakış',icon:Mail},{key:'rules',label:'Kurallar',icon:Workflow},{key:'templates',label:'Şablonlar',icon:FileCode2},{key:'history',label:'Gönderimler',icon:History},{key:'settings',label:'Ayarlar',icon:Settings2}] as const;
type Tab=typeof tabs[number]['key'];
const blankRule=():RuleInput=>({name:'',eventType:'job.published',templateId:'',mode:'off',roles:[],userIds:[],relatedRecipients:false,includeActor:false,priority:100});
function AuditChange({before,after}:{before:Record<string,unknown>|null;after:Record<string,unknown>|null}){
  const labels:Record<string,string>={name:'Ad',mode:'Gönderim',event_type:'Olay',priority:'Öncelik',version:'Şablon sürümü',published_version_id:'Etkin sürüm',paused:'Durduruldu',test_address:'Deneme adresi',recipient:'Alıcı',include_actor:'İşlemi yapan dahil',related_recipients:'İlgili kişiler',user_ids:'Seçili kullanıcılar',roles:'Alıcı rolleri',template_id:'Şablon',newId:'Yeni gönderim'};
  const format=(value:unknown):string=>value==null?'—':typeof value==='boolean'?(value?'Evet':'Hayır'):Array.isArray(value)?value.map(format).join(', ')||'—':modeLabels[value as keyof typeof modeLabels]??USER_ROLE_LABELS[value as UserRole]??eventLabels[value as keyof typeof eventLabels]??String(value);
  const changes=Object.keys(labels).filter(key=>JSON.stringify(before?.[key])!==JSON.stringify(after?.[key]));
  return changes.length?<details className="w-full text-xs"><summary className="oc-tap cursor-pointer">Değişiklik ayrıntıları</summary><dl className="space-y-2 rounded-md bg-muted p-3">{changes.map(key=><div key={key} className="break-words"><dt className="font-medium">{labels[key]}</dt><dd>{format(before?.[key])} → {format(after?.[key])}</dd></div>)}</dl></details>:null;
}
export function HtmlPreview({html,narrow}:{html:string;narrow:boolean}){
  // İçerik sunucuda temizlenir; boş sandbox ek bir tarayıcı sınırıdır.
  const csp="default-src 'none'; img-src https://app.orioncranes.com https://orioncranes.com https://www.orioncranes.com; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'";
  return <div className="overflow-hidden rounded-lg border bg-muted p-2"><iframe title="E-posta önizlemesi" sandbox="" referrerPolicy="no-referrer" className="mx-auto h-[560px] w-full border-0 bg-white transition-[max-width]" style={{maxWidth:narrow?375:800}} srcDoc={`<!doctype html><html lang="tr"><head><meta http-equiv="Content-Security-Policy" content="${csp}"></head><body>${html}</body></html>`}/></div>;
}
export function EmailCenter({initial,previewOnly=false,initialTab,initialJobId}:{initial:CenterData;previewOnly?:boolean;initialTab?:string;initialJobId?:string}){
  const [data,setData]=useState(initial);const [tab,setTab]=useState<Tab>(tabs.some(t=>t.key===initialTab)?initialTab as Tab:'overview');
  const [busy,setBusy]=useState(false);const locked=useRef(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');
  const [jobId,setJobId]=useState('');const [rule,setRule]=useState<RuleInput>(blankRule);
  const [slug,setSlug]=useState('');const [name,setName]=useState('');const [content,setContent]=useState<TemplateContent>(initial.defaultContent);
  const [templateId,setTemplateId]=useState('');const [versionId,setVersionId]=useState('');const [dirty,setDirty]=useState(false);
  const [preview,setPreview]=useState<Preview|null>(null);const [narrow,setNarrow]=useState(false);
  const [relatedUserIds,setRelatedUserIds]=useState<string[]>([]);
  const [paused,setPaused]=useState(Boolean(initial.settings?.paused));const [testAddress,setTestAddress]=useState(initial.settings?.test_address??'');
  const [status,setStatus]=useState('');const [query,setQuery]=useState('');const [historyJob,setHistoryJob]=useState(initialJobId??'');
  const [detail,setDetail]=useState<DeliveryDetail|null>(null);
  async function read(url:string){const r=await fetch(url,{cache:'no-store'});const body=await r.json();if(!r.ok)throw new Error(body.error??'Kayıt okunamadı.');return body;}
  async function reload(page=0){
    if(previewOnly)return;
    const q=new URLSearchParams({page:String(page),status,q:query,jobId:historyJob});
    if(!historyJob)q.delete('jobId');if(!status)q.delete('status');
    setData(await read(`/api/email-center?${q}`));
  }
  async function work(task:()=>Promise<void>){
    if(locked.current)return;locked.current=true;setBusy(true);setError('');setNotice('');
    try{if(previewOnly){setNotice('Bu ekran yalnız görsel önizlemedir.');return;}await task();}
    catch(e){setError(e instanceof Error?e.message:'İşlem tamamlanamadı.');}
    finally{locked.current=false;setBusy(false);}
  }
  async function command(cmd:EmailCommand){
    const r=await fetch('/api/email-center',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cmd)});
    const body=await r.json();if(!r.ok)throw new Error(body.error??'İşlem tamamlanamadı.');return body.result;
  }
  async function loadVersion(id:string,tid=templateId){
    const v=await read(`/api/email-center?detail=version&id=${id}`);const template=data.templates.find(t=>t.id===tid);
    setVersionId(id);setTemplateId(tid);setSlug(template?.slug??'');setName(template?.name??'');setContent(v.content);setDirty(false);setPreview(null);
  }
  function editContent(key:keyof TemplateContent,value:string|string[]){setContent({...content,[key]:value});setDirty(true);setPreview(null);}
  const selectedVersion=data.versions.find(v=>v.id===versionId);
  const selectedTemplate=data.templates.find(t=>t.id===templateId);
  const ruleVersion=data.templates.find(t=>t.id===rule.templateId)?.published_version_id;
  function jobSelector(value:string,onChange:(s:string)=>void,label='Önizleme için iş emri'){
    return <label className="grid gap-1.5 text-sm font-medium">{label}<select className={control} value={value} onChange={e=>onChange(e.target.value)}><option value="">İş seçilmedi</option>{data.jobs.map(j=><option key={j.id} value={j.id}>{j.job_no} · {j.title}</option>)}</select></label>;
  }
  const previewBox=preview&&<section className={`${panel} space-y-4`}>
    <div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">E-posta önizlemesi</h3><p className="text-sm text-muted-foreground">{preview.payload.subject}</p></div><Button variant="outline" className="oc-tap" onClick={()=>setNarrow(!narrow)}>{narrow?'Geniş görünüm':'Dar görünüm'}</Button></div>
    <p className="text-xs text-muted-foreground">ORION &lt;info@orioncranes.com&gt; · Yanıt: info@orioncranes.com</p>
    <HtmlPreview html={preview.payload.html} narrow={narrow}/>
    <details><summary className="oc-tap cursor-pointer text-sm">Düz metin karşılığı</summary><pre className="mt-2 whitespace-pre-wrap break-words rounded-md bg-muted p-3 text-sm">{preview.payload.text}</pre></details>
    {tab==='rules'&&<div className="space-y-2"><h4 className="font-medium">Gerçek alıcılar · {preview.recipients.length}</h4>{preview.recipients.length?preview.recipients.map(p=><div key={p.userId} className="rounded-md border p-3 text-sm"><strong>{p.name}</strong><p className="break-all">{p.email}</p><p className="text-muted-foreground">{p.reasons.map(r=>r.startsWith('Rol: ')?`Rol: ${USER_ROLE_LABELS[r.slice(5) as UserRole]??r.slice(5)}`:r).join(' · ')}</p></div>):<p className="text-sm text-muted-foreground">Bu örnekte uygun alıcı bulunmadı. İlgili kişiye dayanan olaylar için aşağıdaki deneme kişilerini seçin.</p>}<p className="text-xs text-muted-foreground">Deneme modunda yalnız {preview.testAddress} adresine gider. Birden çok kural aynı kişiyi seçerse küçük öncelik değeri olan şablon kullanılır.</p></div>}
  </section>;
  return <div className="min-w-0 space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight">E-posta Merkezi</h1><p className="mt-1 text-sm text-muted-foreground">Kurallar, tasarımlar ve gönderim sonuçları</p></div><Button variant="outline" className="oc-tap" disabled={busy} onClick={()=>work(()=>reload())}><RefreshCw className="size-4"/>Yenile</Button></div>
    <nav aria-label="E-posta Merkezi bölümleri" className="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap">{tabs.map(t=><button key={t.key} onClick={()=>{setTab(t.key);setPreview(null);}} aria-current={tab===t.key?'page':undefined} className={`oc-tap flex min-h-11 items-center gap-2 rounded-lg border px-3 py-2 text-sm ${tab===t.key?'border-primary bg-primary/10 font-semibold text-primary':'bg-card text-muted-foreground hover:bg-muted'}`}><t.icon className="size-4"/>{t.label}</button>)}</nav>
    {error&&<p role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</p>}
    {notice&&<p role="status" className="rounded-lg border bg-muted p-3 text-sm">{notice}</p>}
    {data.settings?.paused&&<p className="flex items-center gap-2 rounded-lg border p-3 text-sm"><AlertCircle className="size-4"/>Otomatik gönderimler durdurulmuş. Bekleyen mesajlar kendiliğinden yeniden açılmaz.</p>}
    {tab==='overview'&&<>
      <div className="grid gap-3 sm:grid-cols-3">{[
        ['Canlı kurallar',data.rules.filter(r=>r.mode==='live').length],['Deneme kuralları',data.rules.filter(r=>r.mode==='test').length],['Gönderim kaydı',data.total],
      ].map(([label,value])=><div key={label} className={panel}><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-semibold tabular-nums">{value}</p></div>)}</div>
      <section className={`${panel} space-y-4`}><h2 className="font-semibold">Bağlantılar</h2><div className="grid gap-3 sm:grid-cols-3">{[['Gönderim servisi',data.connection.sending],['Teslim takibi',data.connection.webhook],['Canlı ortam',data.connection.production]].map(([label,ok])=><p key={String(label)} className="flex items-center gap-2 text-sm">{ok?<CheckCircle2 className="size-4 text-primary"/>:<AlertCircle className="size-4 text-muted-foreground"/>}{label} · {ok?'Hazır':'Yapılandırılacak'}</p>)}</div></section>
      <section className={`${panel} space-y-3`}><h2 className="font-semibold">Son olaylar</h2>{data.events.length?data.events.map(e=><div key={e.id} className="flex flex-wrap justify-between gap-2 border-b py-3 last:border-0"><div><p className="text-sm font-medium">{eventLabels[e.event_type as keyof typeof eventLabels]??e.event_type}</p><p className="text-xs text-muted-foreground">{e.last_error??statusLabels[e.status]} · {date(e.created_at)}</p></div><span className="text-xs">{statusLabels[e.status]}</span></div>):<p className="text-sm text-muted-foreground">Henüz olay kaydı yok. Eski iş emirleri otomatik gönderim oluşturmaz.</p>}</section>
      <section className={`${panel} space-y-3`}><h2 className="font-semibold">Son yönetim işlemleri</h2>{data.audit.length?data.audit.map(a=><div key={a.id} className="flex flex-wrap justify-between gap-2 border-b py-2 text-sm last:border-0"><span>{({'template.save':'Şablon taslağı kaydedildi','template.publish':'Şablon yayımlandı','rule.save':'Kural kaydedildi','settings.save':'Ayarlar değişti','test.send':'Deneme gönderildi','delivery.retry':'Yeniden denendi','delivery.resend':'Tekrar gönderildi'} as Record<string,string>)[a.action]??a.action}</span><span className="text-xs text-muted-foreground">{a.source.startsWith('agent:')?'Codex bağlantısı':a.source==='panel'?'Yönetim paneli':a.source} · {date(a.created_at)}</span><AuditChange before={a.before_value} after={a.after_value}/></div>):<p className="text-sm text-muted-foreground">Henüz değişiklik yok.</p>}</section>
    </>}
    {tab==='templates'&&<div className="space-y-4"><div className="grid gap-4 xl:grid-cols-[250px_minmax(0,1fr)]">
      <aside className={`${panel} space-y-3`}><Button variant="outline" className="oc-tap w-full" onClick={()=>{setTemplateId('');setVersionId('');setName('');setSlug('');setContent(data.defaultContent);setDirty(true);setPreview(null);}}><Plus className="size-4"/>Yeni şablon</Button>
        {data.templates.map(t=><button key={t.id} className={`oc-tap block w-full rounded-lg border p-3 text-left text-sm ${templateId===t.id?'border-primary bg-primary/5':''}`} onClick={()=>work(()=>loadVersion(data.versions.find(v=>v.template_id===t.id)?.id,t.id))}><strong>{t.name}</strong><span className="mt-1 block text-xs text-muted-foreground">{t.published_version_id?'Yayımlanmış sürümü var':'Taslak'}</span></button>)}</aside>
      <section className={`${panel} min-w-0 space-y-4`}><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-sm">Şablon adı<Input value={name} onChange={e=>{setName(e.target.value);setDirty(true);}}/></label><label className="grid gap-1.5 text-sm">Sabit kimlik<Input value={slug} disabled={!!templateId} onChange={e=>{setSlug(e.target.value);setDirty(true);}}/><span className="text-xs text-muted-foreground">Codex bağlantısının kullanacağı kısa kimlik</span></label></div>
        {templateId&&<label className="grid gap-1.5 text-sm">Sürüm<select className={control} value={versionId} onChange={e=>work(()=>loadVersion(e.target.value))}>{data.versions.filter(v=>v.template_id===templateId).map(v=><option key={v.id} value={v.id}>Sürüm {v.version}{selectedTemplate?.published_version_id===v.id?' · Yayında':''} · {date(v.created_at)}</option>)}</select></label>}
        <label className="grid gap-1.5 text-sm">Konu<Input value={content.subject} onChange={e=>editContent('subject',e.target.value)}/></label>
        <label className="grid gap-1.5 text-sm">Gelen kutusu özeti<Input value={content.preheader} onChange={e=>editContent('preheader',e.target.value)}/></label>
        <label className="grid gap-1.5 text-sm">HTML tasarımı<textarea spellCheck={false} className={`${control} min-h-80 font-mono text-sm`} value={content.html} onChange={e=>editContent('html',e.target.value)}/></label>
        <details><summary className="oc-tap cursor-pointer text-sm font-medium">Düz metin ve zorunlu alanlar</summary><div className="mt-3 space-y-3"><textarea aria-label="Düz metin" className={`${control} min-h-36`} value={content.text} onChange={e=>editContent('text',e.target.value)}/><div className="grid gap-2 sm:grid-cols-2">{Object.entries(fieldLabels).map(([key,label])=><label key={key} className="oc-tap flex items-center gap-2 text-sm"><input type="checkbox" checked={content.requiredFields.includes(key as keyof typeof fieldLabels)} onChange={e=>editContent('requiredFields',e.target.checked?[...content.requiredFields,key]:content.requiredFields.filter(k=>k!==key))}/>{label}</label>)}</div></div></details>
        <details><summary className="oc-tap cursor-pointer text-sm font-medium">Codex için kullanılabilir alanlar</summary><div className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(fieldLabels).map(([key,label])=><div key={key} className="rounded-md bg-muted p-2 text-xs"><code>{`{{${key}}}`}</code><p className="mt-1 text-muted-foreground">{label}</p></div>)}</div><p className="mt-3 text-xs text-muted-foreground">İsteğe bağlı satır: {'{{#if job.deliveryDate}}'} … {'{{/if}}'}. Tasarımda satır içi stiller kullanın. Bağlantılar yalnız ORION uygulamasına gider.</p></details>
        <div className="flex flex-wrap gap-2"><Button className="oc-tap" disabled={busy||!name||!slug} onClick={()=>work(async()=>{const v=await command({action:'template.save',data:{slug,name,content}});setTemplateId(v.template_id);setVersionId(v.id);setDirty(false);await reload();setNotice('Yeni taslak sürümü kaydedildi. Yayındaki sürüm değişmedi.');})}>Taslak sürümü kaydet</Button><Button variant="outline" className="oc-tap" disabled={busy||dirty||!versionId} onClick={()=>work(async()=>{await command({action:'template.publish',data:{templateId,versionId}});await reload();setNotice('Seçili sürüm yayımlandı. Yeni olaylar bu sürümü kullanacak.');})}>{selectedTemplate?.published_version_id===versionId?'Bu sürüm yayında':'Bu sürümü yayımla'}</Button></div>
        <p className="text-xs text-muted-foreground">{dirty?'Kaydedilmemiş değişiklikler var. Önizleme için önce taslak sürümü kaydedin.':selectedVersion?`Sürüm ${selectedVersion.version} seçili.`:'Yeni taslak.'}</p>
        {jobSelector(jobId,setJobId)}<div className="flex flex-wrap gap-2"><Button variant="outline" className="oc-tap" disabled={busy||dirty||!versionId} onClick={()=>work(async()=>setPreview(await command({action:'preview',data:{versionId,jobId:jobId||undefined,relatedUserIds:[]}})))}><Eye className="size-4"/>Önizle</Button><Button variant="outline" className="oc-tap" disabled={busy||dirty||!versionId||data.settings.paused} onClick={()=>work(async()=>{await command({action:'test.send',data:{versionId,jobId:jobId||undefined,requestId:crypto.randomUUID()}});await reload();setNotice(`Deneme ${data.settings.test_address} adresine gönderilmek üzere kaydedildi.`);})}><Send className="size-4"/>Deneme gönder</Button></div>
      </section></div>{previewBox}</div>}
    {tab==='rules'&&<div className="space-y-4"><div className="grid gap-4 xl:grid-cols-[300px_minmax(0,1fr)]"><aside className={`${panel} space-y-3`}><Button variant="outline" className="oc-tap w-full" onClick={()=>{setRule(blankRule());setPreview(null);}}><Plus className="size-4"/>Yeni kural</Button>{data.rules.map(r=><button key={r.id} className={`oc-tap block w-full rounded-lg border p-3 text-left ${rule.id===r.id?'border-primary bg-primary/5':''}`} onClick={()=>{setRule(rowToRule(r as RuleRow));setPreview(null);}}><p className="text-sm font-semibold">{r.name}</p><p className="mt-1 text-xs text-muted-foreground">{eventLabels[r.event_type as keyof typeof eventLabels]} · {modeLabels[r.mode as keyof typeof modeLabels]}</p></button>)}</aside>
      <section className={`${panel} space-y-4`}><label className="grid gap-1.5 text-sm">Kural adı<Input value={rule.name} onChange={e=>setRule({...rule,name:e.target.value})}/></label>
        <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-sm">Ne olduğunda?<select className={control} value={rule.eventType} onChange={e=>setRule({...rule,eventType:e.target.value as RuleInput['eventType'],relatedRecipients:false})}>{eventTypes.map(t=><option key={t} value={t}>{eventLabels[t]}</option>)}</select></label><label className="grid gap-1.5 text-sm">Hangi şablon?<select className={control} value={rule.templateId} onChange={e=>setRule({...rule,templateId:e.target.value})}><option value="">Şablon seçin</option>{data.templates.map(t=><option key={t.id} value={t.id}>{t.name}{t.published_version_id?'':' · Yayımlanmamış'}</option>)}</select></label></div>
        <fieldset className="space-y-2"><legend className="mb-2 text-sm font-medium">Alıcı roller</legend><div className="grid gap-2 sm:grid-cols-2">{USER_ROLES.map(role=><label key={role} className="oc-tap flex items-center gap-2 text-sm"><input type="checkbox" checked={rule.roles.includes(role)} onChange={e=>setRule({...rule,roles:e.target.checked?[...rule.roles,role]:rule.roles.filter(r=>r!==role)})}/>{USER_ROLE_LABELS[role]}</label>)}</div></fieldset>
        <details><summary className="oc-tap cursor-pointer text-sm font-medium">Belirli kişiler · {rule.userIds.length} seçili</summary><div className="mt-2 grid max-h-64 gap-2 overflow-y-auto sm:grid-cols-2">{data.people.map(p=><label key={p.id} className="oc-tap flex items-center gap-2 text-sm"><input type="checkbox" checked={rule.userIds.includes(p.id)} onChange={e=>setRule({...rule,userIds:e.target.checked?[...rule.userIds,p.id]:rule.userIds.filter(id=>id!==p.id)})}/>{p.full_name}</label>)}</div></details>
        {!rule.eventType.startsWith('job.')&&<label className="oc-tap flex items-center gap-2 text-sm"><input type="checkbox" checked={rule.relatedRecipients} onChange={e=>setRule({...rule,relatedRecipients:e.target.checked})}/>Olayın ilgili kişileri (atanan / bahsedilen / takip eden)</label>}
        <label className="oc-tap flex items-center gap-2 text-sm"><input type="checkbox" checked={rule.includeActor} onChange={e=>setRule({...rule,includeActor:e.target.checked})}/>İşlemi yapan kişi alıcılar arasındaysa o da alsın</label>
        <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-sm">Çalışma durumu<select className={control} value={rule.mode} onChange={e=>setRule({...rule,mode:e.target.value as RuleInput['mode']})}>{Object.entries(modeLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="grid gap-1.5 text-sm">Öncelik<Input type="number" min={1} max={1000} value={rule.priority} onChange={e=>setRule({...rule,priority:Number(e.target.value)})}/><span className="text-xs text-muted-foreground">Aynı alıcı için küçük sayı önceliklidir.</span></label></div>
        <p className="rounded-lg bg-muted p-3 text-sm">{eventLabels[rule.eventType]} → Seçilen kişiler → {data.templates.find(t=>t.id===rule.templateId)?.name??'Şablon seçilmedi'} → Hemen. {rule.mode==='test'?`Yalnız ${data.settings.test_address} adresine deneme gönderilir.`:rule.mode==='off'?'Bu kural gönderim yapmaz.':'Gerçek alıcılara gönderilir.'}</p>
        <Button className="oc-tap" disabled={busy||!rule.name||!rule.templateId} onClick={()=>work(async()=>{const saved=await command({action:'rule.save',data:rule});setRule(rowToRule(saved));await reload();setNotice('Kural kaydedildi. Geçmiş olaylar için gönderim oluşturulmaz.');})}>Kuralı kaydet</Button>
        <div className="border-t pt-4">{jobSelector(jobId,setJobId)}{rule.relatedRecipients&&<details className="mt-3"><summary className="oc-tap cursor-pointer text-sm">Önizleme olayının ilgili kişileri</summary><div className="grid gap-2 sm:grid-cols-2">{data.people.map(p=><label key={p.id} className="oc-tap flex items-center gap-2 text-sm"><input type="checkbox" checked={relatedUserIds.includes(p.id)} onChange={e=>setRelatedUserIds(e.target.checked?[...relatedUserIds,p.id]:relatedUserIds.filter(id=>id!==p.id))}/>{p.full_name}</label>)}</div></details>}<Button variant="outline" className="oc-tap mt-3" disabled={busy||!ruleVersion} onClick={()=>work(async()=>setPreview(await command({action:'preview',data:{versionId:ruleVersion,jobId:jobId||undefined,rule,relatedUserIds}})))}><Eye className="size-4"/>Bu kural ne yapacak?</Button></div>
      </section></div>{previewBox}</div>}
    {tab==='history'&&<div className="space-y-4"><section className={`${panel} grid items-end gap-3 md:grid-cols-4`}><label className="grid gap-1.5 text-sm">Alıcı adresi<Input value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="grid gap-1.5 text-sm">Sonuç<select className={control} value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tümü</option>{Object.entries(statusLabels).filter(([k])=>k!=='done').map(([k,label])=><option key={k} value={k}>{label}</option>)}</select></label>{jobSelector(historyJob,setHistoryJob,'İş emri')}<Button className="oc-tap" disabled={busy} onClick={()=>work(()=>reload(0))}>Filtrele</Button></section>
      <section className={`${panel} space-y-3`}><div className="flex justify-between"><h2 className="font-semibold">Gönderimler</h2><span className="text-sm text-muted-foreground">{data.total} kayıt</span></div>{data.deliveries.length?data.deliveries.map(d=><button key={d.id} onClick={()=>work(async()=>setDetail(await read(`/api/email-center?detail=delivery&id=${d.id}`)))} className="oc-tap grid w-full gap-2 rounded-lg border p-3 text-left md:grid-cols-[minmax(0,1fr)_140px_160px]"><div className="min-w-0"><p className="break-all text-sm font-medium">{d.recipient_name||d.recipient}</p><p className="break-all text-xs text-muted-foreground">{d.recipient}{d.mode==='test'?' · Deneme':''}</p>{d.last_error&&<p className="mt-1 text-xs text-destructive">{d.last_error}</p>}</div><span className="text-sm">{statusLabels[d.status]}</span><span className="text-xs text-muted-foreground">{date(d.created_at)}</span></button>):<p className="py-6 text-sm text-muted-foreground">Bu filtrede gönderim bulunamadı.</p>}<div className="flex items-center justify-between gap-2"><Button variant="outline" className="oc-tap" disabled={busy||data.page===0} onClick={()=>work(()=>reload(data.page-1))}>Önceki</Button><span className="text-sm">Sayfa {data.page+1}</span><Button variant="outline" className="oc-tap" disabled={busy||(data.page+1)*30>=data.total} onClick={()=>work(()=>reload(data.page+1))}>Sonraki</Button></div></section>
      {detail&&<section className={`${panel} space-y-4`}><div className="flex justify-between gap-2"><h3 className="font-semibold">{detail.payload.subject??'Hazırlanamayan mesaj'}</h3><Button variant="ghost" className="oc-tap" onClick={()=>setDetail(null)}>Kapat</Button></div><p className="text-sm">{statusLabels[detail.status]} · {detail.attempts} deneme</p><ul className="list-inside list-disc text-sm text-muted-foreground">{detail.reasons.map((reason,i)=><li key={i}>{reason}</li>)}</ul>{detail.payload.html&&<HtmlPreview html={detail.payload.html} narrow={false}/>}<details><summary className="oc-tap cursor-pointer text-sm">Teslim zamanları ve düz metin</summary><pre className="mt-2 whitespace-pre-wrap break-words bg-muted p-3 text-xs">{Object.entries(detail.provider_events).map(([type,time])=>`${type}: ${date(time)}`).join('\n')}{'\n\n'}{detail.payload.text}</pre></details><div className="flex flex-wrap gap-2">{detail.status==='failed'&&!detail.provider_id&&<Button variant="outline" className="oc-tap" disabled={busy} onClick={()=>work(async()=>{await command({action:'delivery.retry',data:{deliveryId:detail.id}});setDetail(null);await reload();setNotice('Uygun gönderim aynı kimlikle tekrar denenecek.');})}>Yeniden dene</Button>}{['sent','delivered'].includes(detail.status)&&<Button variant="outline" className="oc-tap" disabled={busy} onClick={()=>work(async()=>{await command({action:'delivery.resend',data:{deliveryId:detail.id,requestId:crypto.randomUUID()}});setDetail(null);await reload();setNotice('Yeni bir gönderim kaydı oluşturuldu.');})}>Aynı mesajı yeni gönderim olarak tekrar gönder</Button>}</div></section>}
    </div>}
    {tab==='settings'&&<section className={`${panel} max-w-2xl space-y-5`}><h2 className="font-semibold">Gönderim ayarları</h2><div className="rounded-lg bg-muted p-3 text-sm"><p>Gönderen: ORION &lt;info@orioncranes.com&gt;</p><p>Yanıt adresi: info@orioncranes.com</p></div><label className="grid gap-1.5 text-sm">Deneme adresi<Input type="email" value={testAddress} onChange={e=>setTestAddress(e.target.value)}/></label><label className="oc-tap flex items-start gap-3 rounded-lg border p-3 text-sm"><input type="checkbox" checked={paused} onChange={e=>setPaused(e.target.checked)} className="mt-1"/><span><strong>Tüm otomatik gönderimleri durdur</strong><span className="mt-1 block text-muted-foreground">Bekleyenler iptal edilir; yeniden açıldığında geçmiş mesajlar topluca gönderilmez. Servise zaten aktarılmış bir e-posta geri alınamaz.</span></span></label><Button className="oc-tap" disabled={busy} onClick={()=>work(async()=>{await command({action:'settings.save',data:{paused,testAddress}});await reload();setNotice('Gönderim ayarları kaydedildi.');})}>Ayarları kaydet</Button><div className="border-t pt-4 text-sm text-muted-foreground"><p>Codex bu merkezin şablon ve kurallarını yetkili bağlantı üzerinden yönetebilir. Gizli anahtarlar bu ekranda gösterilmez.</p><p className="mt-2">Teslim edildi, alıcının e-posta sunucusunun mesajı kabul ettiğini belirtir; okunduğu anlamına gelmez.</p></div></section>}
  </div>;
}
