-- Gerçek üretim verisi üretmez: çağıran betik transaction'ı daima geri alır.
do $$
<<checks>>
declare a uuid; b uuid; adm uuid; f uuid:=gen_random_uuid(); draft uuid:=gen_random_uuid(); direct_id uuid; team_id uuid; board_id uuid; task_id uuid; r jsonb; v integer; n integer;
begin
 select id into a from profiles where role<>'admin' order by created_at limit 1;
 select id into adm from profiles where role='admin' order by created_at limit 1;
 select id into b from profiles where id not in(a,adm) limit 1;
 perform set_config('request.jwt.claim.role','authenticated',true);
 perform set_config('request.jwt.claim.sub',a::text,true);
 set local role authenticated;
 select account_version into v from profiles where id=a;
 perform account_save('PROFİL DOĞRULAMA','555','Özel doğrulama notu',v);
 begin perform account_save('ESKİ SÜRÜM','','',v); raise exception using errcode='Z0001',message='Profil sürümü korunmadı'; exception when serialization_failure then null; end;
 begin update profiles set title='Yetkisiz unvan' where id=a; raise exception using errcode='Z0001',message='Unvan değiştirilebildi'; exception when insufficient_privilege then null; end;
 begin perform team_manage('create','{"name":"Yetkisiz ekip"}',null); raise exception using errcode='Z0001',message='Üye ekip oluşturdu'; exception when insufficient_privilege then null; end;
 begin perform task_command_core('team.create','{"name":"Gizli geçit"}',a); raise exception using errcode='Z0001',message='Eski komut açığı'; exception when insufficient_privilege then null; end;
 perform feedback_begin(f,'Mobil doğrulama geri bildirimi','idea','Panel',0);
 perform feedback_begin(f,'Mobil doğrulama geri bildirimi','idea','Panel',0);
 begin perform feedback_begin(f,'Değişmiş içerik','idea','Panel',0); raise exception using errcode='Z0001',message='Tekrar içeriği değişti'; exception when serialization_failure then null; end;
 perform feedback_submit(f); perform feedback_submit(f);
 perform feedback_begin(draft,'Eksik ek doğrulama','bug','Panel',1);
 begin perform feedback_submit(draft); raise exception using errcode='Z0001',message='Eksik ek kesinleşti'; exception when check_violation then null; end;
 if feedback_detail(f,false)->'item' ? 'read_at' then raise exception 'Yönetim durumu kullanıcıya sızdı'; end if;
 begin select count(read_at) into n from app_feedback; raise exception using errcode='Z0001',message='İç sütun okunabildi'; exception when insufficient_privilege then null; end;
 r:=task_command('create',jsonb_build_object('title','Doğrudan özel doğrulama','visibility','direct','assignee',b),a);
 direct_id:=(r->'task'->>'id')::uuid;
 if (task_snapshot('{"view":"mine","sent":true}',a)->>'total')::int<1 then raise exception 'Gönderdiklerim boş'; end if;
 if exists(select 1 from jsonb_array_elements(task_snapshot('{"view":"team"}',a)->'tasks') t where t->>'id'=direct_id::text) then raise exception 'Özel görev ekipte'; end if;
 perform set_config('request.jwt.claim.sub',b::text,true);
 if exists(select 1 from profile_private_details where user_id=a) then raise exception 'Özel telefon sızdı'; end if;
 if exists(select 1 from app_feedback where id=f) then raise exception 'Başkasının geri bildirimi sızdı'; end if;
 begin perform feedback_submit(f); raise exception using errcode='Z0001',message='Başkasının gönderisi kesinleşti'; exception when insufficient_privilege then null; end;
 if not exists(select 1 from job_tasks where id=direct_id) then raise exception 'Atanan özel görevi göremedi'; end if;
 begin perform task_command('update',jsonb_build_object('id',direct_id,'version',1,'assignee',adm),b); raise exception using errcode='Z0001',message='Sorumlu yeniden atadı'; exception when insufficient_privilege then null; end;
 perform task_command('update',jsonb_build_object('id',direct_id,'version',1,'status','done'),b);
 perform set_config('request.jwt.claim.sub',adm::text,true);
 if exists(select 1 from job_tasks where id=direct_id) then raise exception 'Yönetici özel görevi gördü'; end if;
 if feedback_detail(f,true)->'item'->>'body'<>'Mobil doğrulama geri bildirimi' then raise exception 'Yönetim gönderiyi göremedi'; end if;
 begin perform feedback_detail(draft,true); raise exception using errcode='Z0001',message='Taslak yönetimde'; exception when insufficient_privilege then null; end;
 select count(*) into n from notifications where href='/admin/feedback/'||f;
 if n<>1 then raise exception 'Kişisel bildirim çoğaldı'; end if;
 perform feedback_manage(f,'read',1);
 begin perform feedback_manage(f,'archive',1); raise exception using errcode='Z0001',message='Yönetim sürümü kayboldu'; exception when serialization_failure then null; end;
 perform feedback_manage(f,'archive',2);
 r:=team_manage('create','{"name":"KONTROL EKİBİ","description":"Geçici"}','team-test-0001'); team_id:=(r->'team'->>'id')::uuid;
 if (team_manage('create','{"name":"KONTROL EKİBİ","description":"Geçici"}','team-test-0001')->'team'->>'id')::uuid<>team_id then raise exception 'Ekip çoğaldı'; end if;
 select id into board_id from task_boards tb where tb.team_id=checks.team_id and is_default;
 if board_id is null then raise exception 'Varsayılan pano yok'; end if;
 perform team_manage('members',jsonb_build_object('id',team_id,'version',1,'users',jsonb_build_array(a)),null);
 begin perform task_command('create',jsonb_build_object('title','Dış üye','visibility','team','board_id',board_id,'assignee',b),adm); raise exception using errcode='Z0001',message='Dış üye atandı'; exception when check_violation then null; end;
 task_id:=(task_command('create',jsonb_build_object('title','Ekip atama kontrolü','visibility','team','board_id',board_id,'assignee',a),adm)->'task'->>'id')::uuid;
 perform team_manage('member',jsonb_build_object('id',team_id,'version',2,'user_id',a,'role','remove'),null);
 if (select assignee from job_tasks where id=task_id) is not null then raise exception 'Çıkarılan üyenin açık ataması kaldı'; end if;
 if task_access(task_id,a) then raise exception 'Çıkarılan üye görevi okuyor'; end if;
 perform team_manage('archive',jsonb_build_object('id',team_id,'version',3),null);
 begin perform task_command('update',jsonb_build_object('id',task_id,'version',2,'title','Arşive yazma'),adm); raise exception using errcode='Z0001',message='Arşiv yazılabildi'; exception when insufficient_privilege then null; end;
 perform team_manage('restore',jsonb_build_object('id',team_id,'version',4),null);
 perform task_command('update',jsonb_build_object('id',task_id,'version',2,'title','Geri açılan görev'),adm);
 perform set_config('request.jwt.claim.sub',a::text,true);
 if feedback_detail(f,false)->'item'->>'body'<>'Mobil doğrulama geri bildirimi' then raise exception 'Arşiv kişisel geçmişi sildi'; end if;
 perform task_command('update',jsonb_build_object('id',direct_id,'version',2,'assignee',adm),a);
 perform set_config('request.jwt.claim.sub',b::text,true);
 if exists(select 1 from job_tasks where id=direct_id) then raise exception 'Eski özel sorumlunun erişimi kaldı'; end if;
 reset role;
end $$;
