-- Tamamı çağıran işlemin içinde çalışır ve geri alınır.
do $$
declare a uuid; other_user uuid; t uuid; blocker uuid; child uuid; v int; r jsonb; payload jsonb; n int;
begin
 select id into a from profiles where role='admin' limit 1;
 select id into other_user from profiles where id<>a limit 1;
 perform set_config('request.jwt.claim.role','authenticated',true);
 perform set_config('request.jwt.claim.sub',a::text,true);
 set local role authenticated;
 t:=(task_command('create',jsonb_build_object('title','Tekrar kontrolü','due_date','2028-01-31','assignee',a),a)->'task'->>'id')::uuid;
 payload:=jsonb_build_object('id',t,'version',1,'recurrence',jsonb_build_object('mode','monthly','interval',1),'checklist',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'text','Kontrol','done',true)));
 r:=task_command('workflow',payload,a,null,'workflow-control-1');
 if not (task_command('workflow',payload,a,null,'workflow-control-1')->>'replayed')::boolean then raise exception 'Tekrar anahtarı korunmadı'; end if;
 begin perform task_command('workflow',jsonb_build_object('id',t,'checklist','[]'::jsonb),a); raise exception using errcode='Z0001',message='Sürüm zorunlu değil'; exception when serialization_failure then null; end;
 begin perform task_command('workflow',jsonb_build_object('id',t,'version',2,'recurrence',jsonb_build_object('mode','monthly','interval',0)),a); raise exception using errcode='Z0001',message='Geçersiz tekrar kabul edildi'; exception when check_violation then null; end;
 perform task_command('update',jsonb_build_object('id',t,'version',2,'status','done'),a);
 child:=(task_flow_detail(t)->>'next_task')::uuid;
 if child is null or (select due_date from job_tasks where id=child)<>'2028-02-29'::date or (select checklist->0->>'done' from job_tasks where id=child)<>'false' then raise exception 'Ay sonu veya kontrol listesi aktarımı hatalı'; end if;
 perform task_command('update',jsonb_build_object('id',t,'version',3,'status','todo'),a);
 perform task_command('update',jsonb_build_object('id',t,'version',4,'status','done'),a);
 if (select count(*) from job_tasks where recurrence_parent=t)<>1 then raise exception 'Yeniden tamamlama görev çoğalttı'; end if;
 if task_next_date('2028-02-29','2028-03-03','{"mode":"monthly","interval":1,"day":31}')<>'2028-03-31'::date then raise exception 'Ay sonu çapası kayboldu'; end if;
 if task_next_date('2028-01-01','2028-03-03','{"mode":"after","interval":3}')<>'2028-03-06'::date then raise exception 'Tamamlanma tabanlı tekrar yanlış'; end if;
 blocker:=(task_command('create',jsonb_build_object('title','Ön koşul kontrolü','assignee',a),a)->'task'->>'id')::uuid;
 perform task_command('workflow',jsonb_build_object('id',child,'version',1,'waiting_for',jsonb_build_array(blocker)),a);
 begin perform task_command('workflow',jsonb_build_object('id',blocker,'version',1,'waiting_for',jsonb_build_array(child)),a); raise exception using errcode='Z0001',message='Döngü kabul edildi'; exception when check_violation then null; end;
 begin perform task_command('update',jsonb_build_object('id',child,'version',2,'status','done'),a); raise exception using errcode='Z0001',message='Ön koşul aşılabildi'; exception when check_violation then null; end;
 begin update user_todos set done_at=now() where id=child; raise exception using errcode='Z0001',message='Eski tamamlama ön koşulu aştı'; exception when check_violation then null; end;
 perform task_command('update',jsonb_build_object('id',blocker,'version',1,'status','done'),a);
 if not exists(select 1 from task_inbox where task_id=child and event='unblocked') then raise exception 'Hazır bildirimi eksik'; end if;
 perform task_command('update',jsonb_build_object('id',child,'version',2,'status','done'),a);
 perform task_save_view('Kontrol görünümü','{"view":"mine"}');
 insert into task_reminder_preferences(user_id,quiet_start,quiet_end) values(a,0,0) on conflict(user_id) do update set quiet_start=0,quiet_end=0,enabled=true;
 perform task_refresh_reminders();
 select count(*) into n from task_inbox where user_id=a and event='due_soon';
 perform task_refresh_reminders();
 if (select count(*) from task_inbox where user_id=a and event='due_soon')<>n then raise exception 'Hatırlatıcı çoğaldı'; end if;
 perform set_config('request.jwt.claim.sub',other_user::text,true);
 if exists(select 1 from task_saved_views where user_id=a) or exists(select 1 from task_dependencies where task_id=child) then raise exception 'Özel görünüm/bağlantı sızdı'; end if;
 begin perform task_flow_detail(t); raise exception using errcode='Z0001',message='Özel akış sızdı'; exception when insufficient_privilege then null; end;
 perform set_config('request.jwt.claim.sub',a::text,true);
 t:=(task_command('create',jsonb_build_object('title','Aylık gün değişimi','due_date','2028-01-31','assignee',a),a)->'task'->>'id')::uuid;
 perform task_command('workflow',jsonb_build_object('id',t,'version',1,'recurrence',jsonb_build_object('mode','monthly','interval',1)),a);
 perform task_command('update',jsonb_build_object('id',t,'version',2,'due_date','2028-01-15'),a);
 perform task_command('update',jsonb_build_object('id',t,'version',3,'status','done'),a);
 if (select due_date from job_tasks where recurrence_parent=t)<>'2028-02-15'::date then raise exception 'Yeni termin günü tekrar kuralına yansımadı'; end if;
 t:=(task_command('create',jsonb_build_object('title','Tarih süzgeci kontrolü','due_date',(now() at time zone 'Europe/Istanbul')::date-1,'assignee',a),a)->'task'->>'id')::uuid;
 if not exists(select 1 from jsonb_array_elements(task_snapshot('{"view":"mine","period":"overdue"}',a)->'tasks') j where j->>'id'=t::text) then raise exception 'Geciken görev süzülmedi'; end if;
 perform task_command('update',jsonb_build_object('id',t,'version',1,'due_date',(now() at time zone 'Europe/Istanbul')::date),a);
 if exists(select 1 from jsonb_array_elements(task_snapshot('{"view":"mine","period":"overdue"}',a)->'tasks') j where j->>'id'=t::text) then raise exception 'Bugün geciken sayıldı'; end if;
 if not exists(select 1 from jsonb_array_elements(task_snapshot('{"view":"mine","period":"week"}',a)->'tasks') j where j->>'id'=t::text) then raise exception 'Bugün haftalık ajandada yok'; end if;
 reset role;
end $$;
