-- TMS klima tip kataloğu. Kaynak: tmsgrup.com/tr/{wmu,vks,pks}-serisi/
-- Bu satırlar kapasite hesabı değil, teknik özelliklerdeki tip ön seçimi ve
-- ekipman listesi/datasheet bağlantısı içindir; nihai seçim proje bazında teyit edilir.

insert into public.cat_equipment (kind, brand, model, attrs, datasheet_url, sort) values
  ('air_conditioner', 'TMS', 'PKS-PO', '{"series":"PKS Serisi","application":"panel","service_class":"agır_hizmet","cooling_capacity_kw_min":2,"cooling_capacity_kw_max":4,"ambient_temp_min_c":-10,"ambient_temp_max_c":80,"dust_resistance":"orta","corrosion_resistance":"orta","vibration_resistance":"orta"}'::jsonb, 'https://tmsgrup.com/tr/pks-serisi/', 9000),
  ('air_conditioner', 'TMS', 'WMU', '{"series":"WMU Serisi","application":"industrial","mounting":"duvara_montajlı","cooling_capacity_kw_min":8,"cooling_capacity_kw_max":100,"features":["serbest_soğutma","temiz_hava"],"dust_resistance":"yüksek","corrosion_resistance":"yüksek"}'::jsonb, 'https://tmsgrup.com/tr/wmu-serisi/', 9001),
  ('air_conditioner', 'TMS', 'VKS-VM', '{"series":"VKS Serisi — Orta Hizmet Tipi","application":"industrial","service_class":"orta_hizmet","cooling_capacity_kw_min":2,"cooling_capacity_kw_max":8,"ambient_temp_min_c":-15,"ambient_temp_max_c":80,"dust_resistance":"orta","corrosion_resistance":"orta","vibration_resistance":"orta"}'::jsonb, 'https://tmsgrup.com/tr/vks-serisi/', 9002),
  ('air_conditioner', 'TMS', 'VKS-VC', '{"series":"VKS Serisi — Kompakt Tip","application":"heavy_industrial","service_class":"ağır_hizmet","cooling_capacity_kw_min":2,"cooling_capacity_kw_max":8,"ambient_temp_max_c":95,"dust_resistance":"çok_yüksek","corrosion_resistance":"çok_yüksek","vibration_resistance":"çok_yüksek"}'::jsonb, 'https://tmsgrup.com/tr/vks-serisi/', 9003),
  ('air_conditioner', 'TMS', 'VKS-VP', '{"series":"VKS Serisi — Paket / Monoblok Tip","application":"heavy_industrial","service_class":"ağır_hizmet","cooling_capacity_kw_min":2.5,"cooling_capacity_kw_max":28,"ambient_temp_max_c":95,"dust_resistance":"çok_yüksek","corrosion_resistance":"çok_yüksek","vibration_resistance":"çok_yüksek"}'::jsonb, 'https://tmsgrup.com/tr/vks-serisi/', 9004),
  ('air_conditioner', 'TMS', 'VKS-VS', '{"series":"VKS Serisi — Split Tip","application":"heavy_industrial","service_class":"ağır_hizmet","cooling_capacity_kw_min":2.5,"cooling_capacity_kw_max":48,"ambient_temp_max_c":95,"dust_resistance":"çok_yüksek","corrosion_resistance":"çok_yüksek","vibration_resistance":"çok_yüksek"}'::jsonb, 'https://tmsgrup.com/tr/vks-serisi/', 9005);
