"use client";
import { useState } from "react";
import { RAIL_REFERENCES, railAccessories } from "@/lib/engineering-tools/rails";

const fmt = new Intl.NumberFormat("tr-TR",{maximumFractionDigits:2});
export function RailsTool(){
  const [family,setFamily]=useState("A tipi");
  const choices=RAIL_REFERENCES.filter((row)=>row.family===family);
  const [selected,setSelected]=useState("A45");
  const rail=RAIL_REFERENCES.find((row)=>row.code===selected&&row.family===family)??choices[0];
  const accessories=railAccessories(rail.code);
  const changeFamily=(value:string)=>{setFamily(value); const first=RAIL_REFERENCES.find((row)=>row.family===value); if(first)setSelected(first.code);};
  return <div className="grid gap-5 lg:grid-cols-[20rem_minmax(0,1fr)]"><section className="grid h-fit gap-4 border bg-card p-4"><label className="grid gap-1 text-sm">Ray ailesi<select className="h-10 border bg-background px-3" value={family} onChange={(e)=>changeFamily(e.target.value)}><option>A tipi</option><option>S tipi</option><option>Kare / dikdörtgen</option></select></label><label className="grid gap-1 text-sm">Ray ölçüsü<select className="h-10 border bg-background px-3" value={rail.code} onChange={(e)=>setSelected(e.target.value)}>{choices.map((row)=><option key={row.code}>{row.code}</option>)}</select></label><dl className="grid grid-cols-2 gap-3"><Metric label="Yükseklik" value={`${fmt.format(rail.heightMm)} mm`}/><Metric label="Baş genişliği" value={`${fmt.format(rail.nominalHeadWidthMm)} mm`}/><Metric label="Etkin baş" value={`${fmt.format(rail.effectiveHeadWidthMm)} mm`}/><Metric label="Anma kütlesi" value={`${fmt.format(rail.massKgPerM)} kg/m`}/></dl><RailDiagram family={rail.family} width={rail.nominalHeadWidthMm} height={rail.heightMm}/></section><section className="grid gap-4"><div className="border bg-card p-4"><h3 className="font-semibold">Uygun Crapex krapolar</h3>{accessories.clamps.length?<div className="mt-3 grid gap-2 sm:grid-cols-2">{accessories.clamps.map((clamp)=><div className="border p-3" key={clamp.model}><strong>{clamp.model}</strong><p className="mt-1 text-sm text-muted-foreground">{clamp.boltCount>1?`${clamp.boltCount} adet `:""}{clamp.bolt} T başlı cıvata</p><p className="text-[11px] text-muted-foreground">{clamp.padded?"Pedli":""}{clamp.padded&&clamp.unpadded?" ve ":""}{clamp.unpadded?"pedsiz":""} montaj</p></div>)}</div>:<Empty text="Bu ray için doğrulanmış Crapex eşleşmesi yok."/>}</div><div className="border bg-card p-4"><h3 className="font-semibold">Uygun Beket ray pedleri</h3>{accessories.pads.length?<div className="mt-3 grid gap-3">{accessories.pads.map((pad)=><div className="grid gap-3 border p-3 sm:grid-cols-[1fr_15rem]" key={pad.code}><dl className="grid grid-cols-2 gap-3"><Metric label="Ped" value={pad.code}/><Metric label="Kütle" value={`${fmt.format(pad.massKgPerM)} kg/m`}/><Metric label="Toplam genişlik A" value={`${pad.totalWidthMm} mm`}/><Metric label="Ray destek genişliği D" value={`${pad.supportWidthMm} mm`}/><Metric label="Kalınlık B–C" value={`${pad.thicknessMm[0]}–${pad.thicknessMm[1]} mm`}/></dl><PadDiagram total={pad.totalWidthMm} support={pad.supportWidthMm}/></div>)}</div>:<Empty text="Bu ray için Beket kataloğunda doğrulanmış ped yok."/>}</div></section></div>;
}
function Metric({label,value}:{label:string;value:string}){return <div><dt className="text-[11px] text-muted-foreground">{label}</dt><dd className="font-mono text-sm font-semibold">{value}</dd></div>}
function Empty({text}:{text:string}){return <p className="mt-3 border-l-2 border-amber-500 pl-3 text-sm text-muted-foreground">{text} Tahmini ürün gösterilmez.</p>}
function RailDiagram({family,width,height}:{family:string;width:number;height:number}){const rect=family==="Kare / dikdörtgen";return <svg viewBox="0 0 300 230" className="w-full border bg-background" role="img" aria-label={`${family} ray kesiti`}><g fill="none" stroke="currentColor" strokeWidth="2" className="text-foreground/80">{rect?<rect x="80" y="45" width="140" height="140" className="fill-muted"/>:<><path d="M75 185H225L205 160H176L168 94H205L220 48H80L95 94H132L124 160H95Z" className="fill-muted"/><line x1="80" y1="205" x2="220" y2="205"/><line x1="55" y1="48" x2="55" y2="185"/></>}</g><g fill="currentColor" fontSize="12" className="text-foreground"><text x="120" y="220">b = {fmt.format(width)} mm</text><text x="10" y="120">h = {fmt.format(height)} mm</text></g></svg>}
function PadDiagram({total,support}:{total:number;support:number}){return <svg viewBox="0 0 300 130" className="w-full border bg-background" role="img" aria-label="Ray pedi ölçü şeması"><path d="M25 78H275V96H25Z" className="fill-primary/20 stroke-primary"/><path d="M85 78V50H215V78" fill="none" stroke="currentColor" strokeWidth="2"/><text x="105" y="118" className="fill-foreground" fontSize="12">A {total} mm</text><text x="112" y="42" className="fill-foreground" fontSize="12">D {support} mm</text></svg>}
